<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1531206119171" stop="1531206119210">
  <name>test_screen</name>
  <labels/>
  <test-cases>
    <test-case start="1531206119171" status="failed" stop="1531206119210">
      <name>Test_Screen.test_01</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;test_screen.Test_Screen object at 0x03629490&gt;

    def test_01(self):
        with open('./screen/test.png','rb') as f:
            allure.attach('截图名字',f.read(),allure.attach_type.PNG)
    
&gt;           assert 0
E           assert 0

Scripts\test_screen.py:8: AssertionError</stack-trace>
      </failure>
      <attachments>
        <attachment source="8e694cad-f17b-4a72-9558-d9292abf0372-attachment.png" title="截图名字" type="image/png"/>
      </attachments>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="16496-MainThread"/>
        <label name="host" value="MicroWin10-1721"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
